#!/usr/bin/perl
use strict;
use warnings;

use Path::Class;
use autodie;
 
 #   File Processor is a file processor that can currently read files from a directory
 #   Copyright (C) 2015  Charles Hildebrandt
 #   This program is free software: you can redistribute it and/or modify
 #   it under the terms of the GNU General Public License as published by
 #   the Free Software Foundation, either version 3 of the License, or
 #  (at your option) any later version.
 #
 #   This program is distributed in the hope that it will be useful,
 #   but WITHOUT ANY WARRANTY; without even the implied warranty of
 #   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 #   GNU General Public License for more details.
 #
 #  You should have received a copy of the GNU General Public License
 #  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#my $file_handle = 1; #Define $file_handle to help compiliation



print "Input directory to Read from\n";
my $Directory = <>;
chomp $Directory;
my $dir = dir("$Directory");

sub Read {
        system("Cls");
print "Input file name including extension (I.e. .txt)\n";
my $FileName = <>;
chomp $FileName;
my $file = $dir->file("$FileName");


my $content = $file->slurp();


my $file_handle = $file->openr();


while( my $line = $file_handle->getline() ) {
        print "$line\n";
}
system("Pause");
&Main;
}

#sub Write {
#system("cls");
#print "Input File Name\n";
#my $FileName = <>;
#my $file = $dir->file("$FileName");

#if (-e $FileName) {
#my $file_handle = $file->open('>>');
#} else {
#my $file_handle = $file->openw();
#}

#my @list = ('a', 'list', 'of', 'lines');

#foreach my $line ( @list ) {
#    $file_handle->print($line . "\n");
#}
#}






sub Main {
        for( ; ; ) {
        system("cls");
        print "Welcome to Perl file Processor v 1.0.0\n";
        print "Do you want to Read from a .txt file (1), Change the directory (2), or quit (3)?\n";
        my $Input = <>;
        chomp $Input;
        if ($Input == 1.2) {
                &Write;
        } elsif ($Input == 1) {
                &Read;
        } elsif ($Input == 2) {
        print "Input directory to Read from\n";
        my $Directory = <>;
        chomp $Directory;
        my $dir = dir("$Directory");
        } elsif ($Input == 3) {
           exit;
        } else {
         print "That is not a command";
        }
}
}system("cls");
&Main;
