#!/usr/bin/perl
use strict;
use warnings;

use Path::Class;
use autodie;
 
 #   File Processor is a file processor that can currently read files from a directory
 #   Copyright (C) 2015  Charles Hildebrandt
 #   This program is free software: you can redistribute it and/or modify
 #   it under the terms of the GNU General Public License as published by
 #   the Free Software Foundation, either version 3 of the License, or
 #  (at your option) any later version.
 #
 #   This program is distributed in the hope that it will be useful,
 #   but WITHOUT ANY WARRANTY; without even the implied warranty of
 #   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 #   GNU General Public License for more details.
 #
 #  You should have received a copy of the GNU General Public License
 #  along with this program.  If not, see <http://www.gnu.org/licenses/>.
#Define Variables to help compiliation
# my $FileName = 1;
# my $File = 1;

print "Input directory to Read from\n";
my $Directory = <>;
chomp $Directory;
my $dir = dir("$Directory");

sub Read {
        system("Cls");
print "Input file name including extension (I.e. .txt)\n";
my $FileName = <>;
chomp $FileName;
my $file = $dir->file("$FileName");


my $content = $file->slurp();


my $file_handle = $file->openr();


while( my $line = $file_handle->getline() ) {
        print "$line\n";
}
system("Pause");
&Main;
}

# sub Write {
# system("cls");
# print "Input File Name WITHOUT extension\n";
# my $FileName = <>;
# chomp $FileName;
# my $file = "${Directory}/${FileName}.txt";
# for( ; ; ) {
        # system("cls");
        # print "Would you like to Write (1) or quit (2)?\n";
        # my $Choice = <>;
        # chomp $Choice;
        # if ($Choice == 1) {
                # &Writing;
        # } elsif ($Choice == 2) {
                # &Main;
        # } else {
                # print "That is not an option.\n";
        # }
        # system("pause");
# }
# }

# sub Writing {
# system("cls");
# open OUT, "> $File" or open OUT, ">> $File";
# my $Text = <>;
# chomp $Text;
# print OUT "$Text\n";
# close OUT;
# }

sub Main {
        for( ; ; ) {
        system("cls");
        print "Welcome to Perl file Processor v 1.0.1\n";
        print "Do you want to Read from a .txt file (1), Change the directory (2), or quit (3)?\n";
        my $Input = <>;
        chomp $Input;
        if ($Input == 1.2) {
                &Write;
        } elsif ($Input == 1) {
                &Read;
        } elsif ($Input == 2) {
        print "Input directory to Read from\n";
        my $Directory = <>;
        chomp $Directory;
        my $dir = dir("$Directory");
        } elsif ($Input == 3) {
           exit;
        } else {
         print "That is not a command";
        }
}
}
system("cls");
system("title File Processor 1.0.1");
&Main;
